spring.application.name=api

# SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meetswathi.cse@gmail.com
spring.mail.password=ovcnixzapujuagix
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# IDS alert email configuration
ids.alert.email.enabled=true
ids.alert.email.from=${spring.mail.username}
ids.alert.email.to=meetswathi.cse@gmail.com
ids.alert.email.failure-backoff-ms=5000

# File Integrity Monitoring configuration
ids.fim.directory=sensitive-files
ids.fim.scan-delay-ms=5000
